language: php
services: docker

php:
  - '5.6'

env:
  - PS_VERSION=1.7.5.0
  - PS_VERSION=1.7.5.1
  - PS_VERSION=latest

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install
  - docker-compose up -d

before_script:
  - bash -c 'while [[ "$(curl -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" != "200" ]]; do sleep 5; done'
  - docker exec -u www-data -ti prestashop_ps_mbo cp modules/ps_mbo/ -R admin-dev

script:
  - php vendor/phpunit/phpunit/phpunit tests

  # PHP Stan
  - export PHPSTAN_FILE=phpstan.neon;
  - docker run --rm --volumes-from prestashop_ps_mbo -v $PWD:/web/module -e _PS_ROOT_DIR_=/var/www/html quetzacoalt/phpstan analyse --configuration=/web/module/tests/phpstan/$PHPSTAN_FILE;

after_script:
  - docker ps
  - docker logs prestashop_ps_mbo
