PrestaShop\Module\Mbo\Tab\TabCollection:
  attributes:
    tabs:
      serialized_name: tab_modules_list
PrestaShop\Module\Mbo\Tab\Tab:
  attributes:
    legacyClassName:
      serialized_name: class_name
    displayMode:
      serialized_name: display_type
PrestaShop\Module\Mbo\RecommendedModule\RecommendedModule:
  attributes:
    moduleName:
      serialized_name: name
    position:
      serialized_name: position
