services:
  _defaults:
    public: true

  mbo.adapter.module_collection_data_provider:
    class: 'PrestaShop\Module\Mbo\Adapter\ModuleCollectionDataProvider'
    arguments:
      - '@prestashop.core.admin.data_provider.module_interface'
      - '@prestashop.core.admin.module.repository'
      - '@prestashop.adapter.presenter.module'
      - '@prestashop.core.admin.tab.repository'
      - '@prestashop.adapter.legacy.context'

  mbo.tab.collection_factory:
    class: 'PrestaShop\Module\Mbo\Adapter\TabCollectionFactory'
    arguments:
      - '@mbo.adapter.module_collection_data_provider'

  mbo.tab.collection_provider:
    class: 'PrestaShop\Module\Mbo\Tab\TabCollectionProvider'
    arguments:
      - '@mbo.tab.collection_factory'
      - '@doctrine.cache.provider'
